<?php
require_once 'head.phtml';
?>

<?php
require_once 'header.phtml';
?>

	<!-- Begin page content -->
	<main role="main" class="container">
    	<h1 class="mt-5">HTML skel</h1>
    	<p>tests</p>
    	<ul>
    		<li><a href="">bootstrap</a></li>
    		<li><a href="">jquery</a></li>
    		<li><a href="<?= $BASE . Base::instance()->alias("testJqueryUi") ?>">jquery ui</a></li>
    		<li><a href="">font awesome</a></li>
    		<li><a href="">fat free framework</a></li>
    	</ul>
	</main>

<?php
require_once 'footer.phtml';
?>

<?php
require_once 'foot.phtml';
?>
