<?php
require_once __DIR__.'/../layout/head.phtml';
?>

<?php
require_once __DIR__.'/../layout/header.phtml';
?>

<<style>
<!--
.carousel {
    background-color: #ddd;
}

.carousel-item.active,
.carousel-item-next,
.carousel-item-prev{
    display:block;
}
-->
</style>

	<!-- Begin page content -->
	<main role="main" class="container">
    	<h1 class="mt-5">HTML skel</h1>
    	<h3>bootstrap test</h3>
    	
	</main>
	
	
	
<div class="container">
	<button type="button" class="btn btn-success">Success</button>
    <div id="carouselContent" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner" role="listbox">
            <div class="carousel-item active text-center p-4">
                 <p>lorem ipsum (imagine longer text)</p>
            </div>
            <div class="carousel-item text-center p-4">
                
                <p>lorem ipsum (imagine longer text)</p>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselContent" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselContent" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>
	
<?php
require_once __DIR__.'/../layout/footer.phtml';
?>


<?php
require_once __DIR__.'/../layout/foot.phtml';
?>

<script>
$('.carousel').carousel();
</script>