<?php
require_once __DIR__ . '/../layout/head.phtml';
?>

<?php
require_once __DIR__ . '/../layout/header.phtml';
?>

<!-- Begin page content -->
<main role="main" class="container">
	<h1 class="mt-5">HTML skel</h1>
	<h3>jquery ui test</h3>
</main>

<div id="dialog-confirm" title="Empty the recycle bin?">
	<p>
		<span class="ui-icon ui-icon-alert" style="float: left; margin: 12px 12px 20px 0;"></span>These items will be
		permanently deleted and cannot be recovered. Are you sure?
	</p>
</div>


<?php
require_once __DIR__ . '/../layout/footer.phtml';
?>


<?php
require_once __DIR__ . '/../layout/foot.phtml';
?>

<script>
  $( function() {
	var bootstrapButton = $.fn.button.noConflict() // return $.fn.button to previously assigned value
	$.fn.bootstrapBtn = bootstrapButton // give $().bootstrapBtn the Bootstrap functionality
	
    $( "#dialog-confirm" ).dialog({
      resizable: false,
      height: "auto",
      width: 400,
      modal: true,
      buttons: {
        "Delete all items": function() {
          $( this ).dialog( "close" );
        },
        Cancel: function() {
          $( this ).dialog( "close" );
        }
      }
    });
  } );
</script>